plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = "1.3.2"
group = "com.demonz"

base {
    archivesName = 'craftyai-forge-26'
}

repositories {
    mavenCentral()
}

neoForge {
    version = '26.1.2.94'
}

dependencies {
    implementation project(':craftyai-common')
    implementation 'com.google.code.gson:gson:2.10.1'
}

sourceSets {
    main {
        java {
            srcDir project(':craftyai-common').file('src/main/java')
        }
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn ':craftyai-common:classes'
    from project(':craftyai-common').sourceSets.main.output
}
