modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/zCkE44hsBR"

[[mods]]
modId = "craftyai"
version = "${version}"
displayName = "CraftyAI"
description = "Neural AI Companion for Minecraft - DemonZ Development"
authors = "DemonZ Development"
displayURL = "https://craftyai.pages.dev"
logoFile = "logo.png"

[[dependencies.craftyai]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftyai]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
